CREATE TABLE IF NOT EXISTS categories
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(250) UNIQUE                     NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id)

);

CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name  VARCHAR(250)                            NOT NULL,
    user_email VARCHAR(50) UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location_lat DECIMAL                                 NOT NULL,
    location_lon DECIMAL                                 NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    location_id        BIGINT                                  NOT NULL,
    title              VARCHAR                                 NOT NULL,
    annotation         VARCHAR                                 NOT NULL,
    description        VARCHAR                                 NOT NULL,
    state              VARCHAR                                 NOT NULL,
    date               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    published          TIMESTAMP WITHOUT TIME ZONE,
    participant_limit  BIGINT,
    paid               BOOLEAN                                 NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (event_id),
    FOREIGN KEY (category_id)
        REFERENCES categories (category_id) ON DELETE CASCADE,
    FOREIGN KEY (initiator_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY (location_id)
        REFERENCES locations (location_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned         BOOLEAN                                 NOT NULL,
    title          VARCHAR                                 NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (compilation_id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    FOREIGN KEY (compilation_id)
        REFERENCES compilations (compilation_id) ON DELETE CASCADE,
    FOREIGN KEY (event_id)
        REFERENCES events (event_id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS requests
(
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    status     VARCHAR                                 NOT NULL,
    FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY (event_id)
        REFERENCES events (event_id) ON DELETE CASCADE,
    CONSTRAINT pk_requests PRIMARY KEY (request_id)
);