DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app       VARCHAR(250)                            NOT NULL,
    uri       VARCHAR(250)                            NOT NULL,
    ip        VARCHAR(250)                            NOT NULL,
    timestamp timestamp without time zone             NOT NULL
);