DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    hit_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hit_app       VARCHAR,
    hit_uri       VARCHAR,
    hit_ip        VARCHAR,
    hit_timestamp TIMESTAMP WITHOUT TIME ZONE
);